#!/usr/bin/expect

# (on some systems we use "#!/usr/bin/tclsh"

#-- If we start reading too soon, we end up printing a bunch of blank lines

  after 50

#   +---------+
#---| commify |---
#   +---------+

  proc commify {num {sep ,}} {
    while {[regsub {^([-+]?\d+)(\d\d\d)} $num "\\1$sep\\2" num]} {}
    return $num
  }

#   +------+
#---| MAIN |---
#   +------+

  while {![eof stdin]} {

    gets stdin line

    if {[string length $line] == 0} {
      if {[eof stdin]} {
        break
      }
    }

    set line [string trim $line]

    if {$line != ""} {
      foreach word [split $line] {
        if {[regexp {^\d{3}\d+$} $word]} {
          set commified_word [commify $word]
          regsub "$word" $line $commified_word line
        }
      }
    }

    puts $line

  }

