#!/bin/bash

{
    while [ 1 ]
    do
        sleep 0.033
        python -c "print(
              100*'123456789ABCDEF ' + '\n'
            + 100*'23456789ABCDEF 1' + '\n'
            + 100*'3456789ABCDEF 12' + '\n'
            + 100*'456789ABCDEF 123' + '\n'
            + 100*'56789ABCDEF 1234' + '\n'
            + 100*'6789ABCDEF 12345' + '\n'
            + 100*'789ABCDEF 123456' + '\n'
            + 100*'89ABCDEF 1234567' + '\n'
            + 100*'9ABCDEF 12345678' + '\n'
            + 100*'ABCDEF 123456789' + '\n'
            + 100*'BCDEF 123456789A' + '\n'
            + 100*'CDEF 123456789AB' + '\n'
            + 100*'DEF 123456789ABC' + '\n'
            + 100*'EF 123456789ABCD' + '\n'
            + 100*'F 123456789ABCDE')"
    done
} | cut -c-$((`tput cols`-25))
